- src/main/java/com/example/ondongnae/backend/allergy/model/Allergy.java
- src/main/java/com/example/ondongnae/backend/category/model/MainCategory.java
- src/main/java/com/example/ondongnae/backend/category/model/StoreSubCategory.java
- src/main/java/com/example/ondongnae/backend/category/model/SubCategory.java
- src/main/java/com/example/ondongnae/backend/course/model/Course.java
- src/main/java/com/example/ondongnae/backend/course/model/CourseStore.java
- src/main/java/com/example/ondongnae/backend/course/model/Option.java
- src/main/java/com/example/ondongnae/backend/market/model/Market.java
- src/main/java/com/example/ondongnae/backend/member/model/Member.java
- src/main/java/com/example/ondongnae/backend/menu/model/Menu.java
- src/main/java/com/example/ondongnae/backend/menu/model/MenuAllergy.java
- src/main/java/com/example/ondongnae/backend/store/model/BusinessHour.java
- src/main/java/com/example/ondongnae/backend/store/model/DayOfWeek.java
- src/main/java/com/example/ondongnae/backend/store/model/Store.java
- src/main/java/com/example/ondongnae/backend/store/model/StoreImage.java
- src/main/java/com/example/ondongnae/backend/store/model/StoreIntro.java
closed #3 
- 나머지 회원, 시장, 영업시간, 가게, 가게 이미지, 가게 설명, 옵션 모델 생성
- 패키지 구조 리팩토링
- 계층형 구조에서 도메인형 구조로 리팩토링 진행했습니다.
> 3 feat 나머지 모델 생성

- .gitignore
- build.gradle
- src/main/java/com/example/ondongnae/backend/course/model/Option.java
- src/main/java/com/example/ondongnae/backend/global/config/security/JwtAuthenticationFilter.java
- src/main/java/com/example/ondongnae/backend/global/config/security/JwtProvider.java
- src/main/java/com/example/ondongnae/backend/global/config/security/SecurityConfig.java
- src/main/java/com/example/ondongnae/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/ondongnae/backend/global/exception/JwtAuthenticationException.java
- src/main/java/com/example/ondongnae/backend/global/response/CustomResponse.java
- src/main/java/com/example/ondongnae/backend/member/controller/AuthController.java
- src/main/java/com/example/ondongnae/backend/member/dto/SignUpDto.java
- src/main/java/com/example/ondongnae/backend/member/dto/TokenDto.java
- src/main/java/com/example/ondongnae/backend/member/model/Member.java
- src/main/java/com/example/ondongnae/backend/member/repository/MemberRepository.java
- src/main/java/com/example/ondongnae/backend/member/service/AuthService.java
- src/main/java/com/example/ondongnae/backend/store/model/Store.java
- src/main/java/com/example/ondongnae/backend/store/model/StoreImage.java
- src/main/resources/application.properties
가게 등록 제외한 회원가입/ 로그인 기능 구현
응답 형식 통일을 위한 CustomResponse 클래스 작성
JWT 구현
> [Feat] 가게 등록 제외 회원가입/ 로그인 기능 구현

- src/main/java/com/example/ondongnae/backend/global/exception/BaseException.java
- src/main/java/com/example/ondongnae/backend/global/exception/ErrorCode.java
- src/main/java/com/example/ondongnae/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/ondongnae/backend/global/response/ApiResponse.java
- 응답 형식 통일: ApiResponse(succes, data, code, message)
- 전역 에러 처리
- ErrorCode(enum): HttpStatus + code + message를 중앙에서 관리
- BaseException: 모든 예외의 베이스
- GlobalExceptionHandler: 커스터/유효성/최종 예외 공통 처리
- JwtAuthenticationException(삭제 필요) 대신 ErrorCode.INVALID_TOKEN 사용 => 관련 로직 수정 필요
-  기존 CustomResponse(삭제 필요) -> ApiResponse 로직 수정 필요
> [Feature] 전역 에러 처리 & 응답 형식 수정

- build.gradle
- src/main/java/com/example/ondongnae/backend/global/exception/ErrorCode.java
- src/main/java/com/example/ondongnae/backend/menu/repository/MenuRepository.java
- src/main/java/com/example/ondongnae/backend/store/controller/StoreController.java
- src/main/java/com/example/ondongnae/backend/store/dto/StoreDetailResponse.java
- src/main/java/com/example/ondongnae/backend/store/repository/BusinessHourRepository.java
- src/main/java/com/example/ondongnae/backend/store/repository/StoreIntroRepository.java
- src/main/java/com/example/ondongnae/backend/store/repository/StoreRepository.java
- src/main/java/com/example/ondongnae/backend/store/service/StoreDetailService.java
closed #8 
- StoreDetailResponse DTO 생성: header/menuTab/infoTab/map 섹션 분리
- StoreDetailService 구현
- StoreRepository: 기본 정보, 이미지, 시장 정보 조회
- MenuRepository: 메뉴 & 알레르기 정보 조회
- BusinessHourRepository: 영업시간 조회
- StoreIntroRepository: 언어별 소개 조회
- 현재 영업 상태(isOpen, 오늘 여는/닫는 시간, 휴무 여부) 계산 로직 추가
- Controller 엔드포인트 추가(GET /stores/{storeId}?lang={lang} 
- ErrorCode 추가(STORE_NOT_FOUND, BUSINESS_HOUR_NOT_FOUND)
> [Feat] 가게 상세 조회 기능 구현

- src/main/java/com/example/ondongnae/backend/global/exception/ErrorCode.java
- src/main/java/com/example/ondongnae/backend/member/service/AuthService.java
- src/main/java/com/example/ondongnae/backend/menu/controller/MenuController.java
- src/main/java/com/example/ondongnae/backend/menu/dto/ManualMenuCreateRequest.java
- src/main/java/com/example/ondongnae/backend/menu/dto/ManualMenuCreateResponse.java
- src/main/java/com/example/ondongnae/backend/menu/model/Menu.java
- src/main/java/com/example/ondongnae/backend/menu/service/MenuService.java
- src/main/java/com/example/ondongnae/backend/store/repository/StoreRepository.java
closed #13 
- AuthService: 로그인한 사용자의 토큰에서 인증 정보 추출 -> 해당 사용자의 Member, storeId 조회 메서드 추가
- StoreRepository: memberId로 Store 조회 기능 추가
- 요청, 응답 dto 생성
- MenuController, MenuService 수기 메뉴 저장 로직 구현
> [Feat] 메뉴 저장 기능 구현

- src/main/java/com/example/ondongnae/backend/currency/controller/ExchangeRateController.java
- src/main/java/com/example/ondongnae/backend/currency/dto/ExchangeRateDto.java
- src/main/java/com/example/ondongnae/backend/currency/dto/ExchangeRateResponseDto.java
- src/main/java/com/example/ondongnae/backend/currency/dto/PriceWithRateResponseDto.java
- src/main/java/com/example/ondongnae/backend/currency/service/ExchangeRateService.java
- src/main/java/com/example/ondongnae/backend/global/exception/GlobalExceptionHandler.java
closed #15 
환율 조회 및 환율 반영하여 가격 변환 기능 구현
쿼리 파라미터 관련 에러 핸들러 추가
> [Feat] 환율 조회 및 가격 계산 기능 구현

- src/main/java/com/example/ondongnae/backend/store/controller/BusinessHourController.java
- src/main/java/com/example/ondongnae/backend/store/dto/BusinessHourRequest.java
- src/main/java/com/example/ondongnae/backend/store/model/BusinessHour.java
- src/main/java/com/example/ondongnae/backend/store/repository/BusinessHourRepository.java
- src/main/java/com/example/ondongnae/backend/store/service/BusinessHourService.java
closed #19 
가게의 요일별 영업시간을 저장하는 기능입니다.
- 기존 영업시간 전체 삭제 후 새 데이터 저장하는 방식
- 요일 중복, 요일명, 시간 형식 검증 및 예외 처리
- BusinessHour 필드명 수정 있습니다. pull 받고 create-drop 한 번 해주세요 !
> [Feat] 영업 시간 저장 기능 구현

- src/main/java/com/example/ondongnae/backend/store/controller/BusinessHourController.java
- src/main/java/com/example/ondongnae/backend/store/dto/BusinessHourResponse.java
- src/main/java/com/example/ondongnae/backend/store/service/BusinessHourService.java
closed #23 
- 주간 영업 시간 조회 기능 입니다.
- 가게명 (한)까지 함께 반환하도록 구현
> [Feat} 영업 시간 전체 조회 기능 구현

- src/main/java/com/example/ondongnae/backend/category/repository/StoreSubCategoryRepository.java
- src/main/java/com/example/ondongnae/backend/global/service/LatLngService.java
- src/main/java/com/example/ondongnae/backend/map/controller/MapController.java
- src/main/java/com/example/ondongnae/backend/map/dto/CategoryDto.java
- src/main/java/com/example/ondongnae/backend/map/dto/MapInitDataResponseDto.java
- src/main/java/com/example/ondongnae/backend/map/dto/RandomStoreDto.java
- src/main/java/com/example/ondongnae/backend/map/service/MapService.java
- src/main/java/com/example/ondongnae/backend/store/repository/StoreRepository.java
- src/main/java/com/example/ondongnae/backend/store/service/StoreDetailService.java
- src/main/java/com/example/ondongnae/backend/store/service/StoreService.java
시장 리스트, 대분류/소분류 리스트, 랜덤 가게 3개 정보 리스트 반환하는 API 추가
> [Feat] 지도 초기 데이터 조회 구현

- src/main/java/com/example/ondongnae/backend/course/controller/CourseController.java
- src/main/java/com/example/ondongnae/backend/course/service/CourseRecommendationService.java
- src/main/java/com/example/ondongnae/backend/global/config/security/SecurityConfig.java
- src/main/java/com/example/ondongnae/backend/map/controller/MapController.java
- src/main/java/com/example/ondongnae/backend/member/service/AuthService.java
- src/main/java/com/example/ondongnae/backend/store/controller/StoreController.java
- src/main/java/com/example/ondongnae/backend/store/dto/StoreDescriptionDto.java
- src/main/java/com/example/ondongnae/backend/store/model/StoreIntro.java
- src/main/java/com/example/ondongnae/backend/store/service/StoreDescriptionService.java
- src/main/java/com/example/ondongnae/backend/store/service/StoreDetailService.java
- src/main/java/com/example/ondongnae/backend/store/service/StoreService.java
closed #31 
사용자가 설정한 언어를 전달하는 방식을 쿠키 -> Accept-Language 헤더로 변경
연동을 위한 CORS 관련 설정 추가
가게 설명 조회 - 쿼리 파라미터 ver에 short, long, both를 지정하여 원하는 값을 받아오도록 했습니다
가게 설명 수정 - 쿼리 파라미터 ver에 short, long을 지정하여 각 페이지에서 각 값을 수정할 수 있도록 했습니다.
가게 설명 조회 both
가게 설명 조회 short
가게 설명 조회 long
가게 설명 수정 long
가게 설명 수정 반영
> [Feat] 가게 설명 조회 및 수정

- src/main/java/com/example/ondongnae/backend/map/controller/MapController.java
- src/main/java/com/example/ondongnae/backend/member/dto/RegisterStoreDto.java
가게 등록 요청 DTO에서 전화번호에 @NotNull을 제거했습니다.
가게 검색 컨트롤러에서 keyword에 @ NotBlank를 추가했습니다.
> [Feat] 가게 전화번호 미입력 허용 / 가게 검색 시 빈 문자열 허용 X 하도록 수정

- src/main/java/com/example/ondongnae/backend/course/dto/RandomCourseDto.java
- src/main/java/com/example/ondongnae/backend/course/dto/RecommendedCourseStoreDto.java
- src/main/java/com/example/ondongnae/backend/course/service/CourseRecommendationService.java
- src/main/java/com/example/ondongnae/backend/course/service/CourseService.java
코스 상세 조회/ 코스 랜덤 추천 조회 시 이미지도 반환하도록 수정
> [Feat] 코스 상세 조회/ 코스 랜덤 추천 조회 시 이미지도 반환하도록 수정

- src/main/java/com/example/ondongnae/backend/menu/dto/ManualMenuCreateResponse.java
- src/main/java/com/example/ondongnae/backend/menu/service/MenuService.java
> [Feat] 메뉴 저장 Response Body 수정

- src/main/java/com/example/ondongnae/backend/currency/controller/ExchangeRateController.java
- src/main/java/com/example/ondongnae/backend/global/service/TranslateService.java
- src/main/java/com/example/ondongnae/backend/map/service/MapStoreFilterService.java
- src/main/java/com/example/ondongnae/backend/market/service/MarketService.java
- src/main/java/com/example/ondongnae/backend/member/controller/AuthController.java
- src/main/java/com/example/ondongnae/backend/member/service/AuthService.java
회원가입 시에는 토큰 발급 (로그인 처리)하지 않도록 변경했습니다.
불필요한 import문 제거했습니다.
> [Feat] 회원가입 시에는 토큰 발급 안하도록 변경

- src/main/java/com/example/ondongnae/backend/store/service/StoreDetailService.java
> [Feat] 가게 상세 조회 시 영업 시간 null 허용

- src/main/java/com/example/ondongnae/backend/allergy/cononical/CanonicalAllergy.java
- src/main/java/com/example/ondongnae/backend/allergy/dto/AllergyExtractResponse.java
- src/main/java/com/example/ondongnae/backend/allergy/service/AllergyService.java
closed #50 
- 한국어 알레르기 성분도 반환하게 수정
> [Feat} 알레르기 추출 Response Body 수정

- src/main/java/com/example/ondongnae/backend/category/repository/StoreSubCategoryRepository.java
- src/main/java/com/example/ondongnae/backend/course/service/CourseService.java
- src/main/java/com/example/ondongnae/backend/member/controller/MyProfileController.java
- src/main/java/com/example/ondongnae/backend/member/service/AuthService.java
- src/main/java/com/example/ondongnae/backend/member/service/MemberService.java
- src/main/java/com/example/ondongnae/backend/store/model/Store.java
closed #51
회원 탈퇴 기능 구현했습니다.
회원 탈퇴 시 Store 엔티티는 삭제하지 않고 memberId (FK)만 null로 변경하도록 했습니다.
> [Feat] 회원 탈퇴 기능 구현

- src/main/java/com/example/ondongnae/backend/menu/service/MenuService.java
closed #56 
- 메뉴 저장 시 기존 메뉴 삭제
- 외래키 법칙에 따라 MenuAllergy 테이블 먼저 삭제후 Menu 테이블 삭제
> [Feat} OCR/직접 메뉴 저장 시 기존 메뉴 삭제

- src/main/java/com/example/ondongnae/backend/menu/dto/ManualMenuCreateResponse.java
- src/main/java/com/example/ondongnae/backend/menu/service/MenuService.java
closed #58 
음식 관련 카테고리 가게인 경우 canExtractAllergy가 true
> [Feat] 알레르기 추출 버튼 플래그 추가

- Dockerfile
- docker-compose.yml
> [Feat] DockerFile, docker-compose.yml 작성

- src/main/java/com/example/ondongnae/backend/store/service/StoreDescriptionService.java
> [Feat] 가게 설명 수정 시 외국어도 업데이트 되도록 수정
